// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { useAuthors } from '~~/nsdb/models/authors'
import { useCategories } from '~~/nsdb/models/categories'
import { useComponentRecords } from '~~/nsdb/models/component_records'
import { useMessages } from '~~/nsdb/models/messages'
import { usePlaylists } from '~~/nsdb/models/playlists'
import { usePosts } from '~~/nsdb/models/posts'
import { useProfiles } from '~~/nsdb/models/profiles'
import { useTags } from '~~/nsdb/models/tags'
import { useTracks } from '~~/nsdb/models/tracks'

export function useNsdbModel(model: string, opts: { store?: boolean } = {}) {
	switch (model) {
				case 'authors':
			return useAuthors(opts)
		case 'categories':
			return useCategories(opts)
		case 'component_records':
			return useComponentRecords(opts)
		case 'messages':
			return useMessages(opts)
		case 'playlists':
			return usePlaylists(opts)
		case 'posts':
			return usePosts(opts)
		case 'profiles':
			return useProfiles(opts)
		case 'tags':
			return useTags(opts)
		case 'tracks':
			return useTracks(opts)
		default:
			throw new Error(`Aucun model nsdb enregistré pour le modèle "${model}"`)
	}
}
