// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { useComponentRecords } from '~~/nsdb/models/component_records'
import { useGears } from '~~/nsdb/models/gears'
import { usePlaylists } from '~~/nsdb/models/playlists'
import { useProfiles } from '~~/nsdb/models/profiles'
import { useSamples } from '~~/nsdb/models/samples'
import { useSongs } from '~~/nsdb/models/songs'

export function useNsdbModel(model: string, opts: { store?: boolean } = {}) {
	switch (model) {
				case 'component_records':
			return useComponentRecords(opts)
		case 'gears':
			return useGears(opts)
		case 'playlists':
			return usePlaylists(opts)
		case 'profiles':
			return useProfiles(opts)
		case 'samples':
			return useSamples(opts)
		case 'songs':
			return useSongs(opts)
		default:
			throw new Error(`Aucun model nsdb enregistré pour le modèle "${model}"`)
	}
}
