// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type AuthorsRow = Tables<'authors'>

/** ----- Schema (entities) for authors ----- */
export const AuthorsSchema = {
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	name: { label: 'Name', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
} as const satisfies Partial<Record<keyof AuthorsRow, EntityField>>

export const AuthorsRelations: EntityRelation[] = [
  {
    "alias": "receiver_messages",
    "kind": "hasMany",
    "direction": "inverse",
    "nullable": false,
    "referencedTable": "messages",
    "embedResource": "messages",
    "localColumns": [
      "id"
    ],
    "referencedColumns": [
      "receiver_id"
    ],
    "foreignKeyName": "messages_receiver_id_fkey",
    "composite": false
  },
  {
    "alias": "sender_messages",
    "kind": "hasMany",
    "direction": "inverse",
    "nullable": false,
    "referencedTable": "messages",
    "embedResource": "messages",
    "localColumns": [
      "id"
    ],
    "referencedColumns": [
      "sender_id"
    ],
    "foreignKeyName": "messages_sender_id_fkey",
    "composite": false
  },
  {
    "alias": "posts",
    "kind": "hasMany",
    "direction": "inverse",
    "nullable": false,
    "referencedTable": "posts",
    "embedResource": "posts",
    "localColumns": [
      "id"
    ],
    "referencedColumns": [
      "author_id"
    ],
    "foreignKeyName": "posts_author_id_fkey",
    "composite": false
  }
]
