// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type CategoriesRow = Tables<'categories'>

/** ----- Schema (entities) for categories ----- */
export const CategoriesSchema = {
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	name: { label: 'Name', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
	parent_id: { label: 'Parent id', type: 'relation', required: false, selectable: true, editable: true, insertable: true, updatable: true, nullable: true, hasDefault: false, databaseType: "uuid", defaultExpression: null, relation: { alias: 'parent', kind: 'belongsTo', direction: 'forward', referencedTable: 'categories', embedResource: 'parent_id', localColumns: ['parent_id'], referencedColumns: ['id'], foreignKeyName: 'categories_parent_id_fkey', nullable: true, composite: false } },
} as const satisfies Partial<Record<keyof CategoriesRow, EntityField>>

export const CategoriesRelations: EntityRelation[] = [
  {
    "alias": "parent",
    "kind": "belongsTo",
    "direction": "forward",
    "nullable": true,
    "referencedTable": "categories",
    "embedResource": "parent_id",
    "localColumns": [
      "parent_id"
    ],
    "referencedColumns": [
      "id"
    ],
    "foreignKeyName": "categories_parent_id_fkey",
    "composite": false
  },
  {
    "alias": "children",
    "kind": "hasMany",
    "direction": "inverse",
    "nullable": false,
    "referencedTable": "categories",
    "embedResource": "categories",
    "localColumns": [
      "id"
    ],
    "referencedColumns": [
      "parent_id"
    ],
    "foreignKeyName": "categories_parent_id_fkey",
    "composite": false
  }
]
