// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type MessagesRow = Tables<'messages'>

/** ----- Schema (entities) for messages ----- */
export const MessagesSchema = {
	body: { label: 'Body', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	receiver_id: { label: 'Receiver id', type: 'relation', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "uuid", defaultExpression: null, relation: { alias: 'receiver', kind: 'belongsTo', direction: 'forward', referencedTable: 'authors', embedResource: 'authors', localColumns: ['receiver_id'], referencedColumns: ['id'], foreignKeyName: 'messages_receiver_id_fkey', nullable: false, composite: false } },
	sender_id: { label: 'Sender id', type: 'relation', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "uuid", defaultExpression: null, relation: { alias: 'sender', kind: 'belongsTo', direction: 'forward', referencedTable: 'authors', embedResource: 'authors', localColumns: ['sender_id'], referencedColumns: ['id'], foreignKeyName: 'messages_sender_id_fkey', nullable: false, composite: false } },
} as const satisfies Partial<Record<keyof MessagesRow, EntityField>>

export const MessagesRelations: EntityRelation[] = [
  {
    "alias": "receiver",
    "kind": "belongsTo",
    "direction": "forward",
    "nullable": false,
    "referencedTable": "authors",
    "embedResource": "authors",
    "localColumns": [
      "receiver_id"
    ],
    "referencedColumns": [
      "id"
    ],
    "foreignKeyName": "messages_receiver_id_fkey",
    "composite": false
  },
  {
    "alias": "sender",
    "kind": "belongsTo",
    "direction": "forward",
    "nullable": false,
    "referencedTable": "authors",
    "embedResource": "authors",
    "localColumns": [
      "sender_id"
    ],
    "referencedColumns": [
      "id"
    ],
    "foreignKeyName": "messages_sender_id_fkey",
    "composite": false
  }
]
