// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type PlaylistsRow = Tables<'playlists'>

/** ----- Schema (entities) for playlists ----- */
export const PlaylistsSchema = {
	created_at: { label: 'Created at', type: 'datetime', required: false, selectable: true, editable: true, insertable: true, updatable: true, hidden: true, nullable: false, hasDefault: true, databaseType: "timestamp with time zone", defaultExpression: "now()" },
	description: { label: 'Description', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: true, nullable: true, hasDefault: false, databaseType: "text", defaultExpression: null },
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	metadata: { label: 'Metadata', type: 'json', required: false, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: true, databaseType: "jsonb", defaultExpression: "'{}'::jsonb" },
	status: { label: 'Status', type: 'select', required: false, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: true, databaseType: "playlist_status", defaultExpression: "'draft'::playlist_status", options: Enums.PlaylistStatusValues.map(v => ({ label: String(v), value: v })) },
	tags: { label: 'Tags', type: 'array', required: false, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: true, databaseType: "text[]", defaultExpression: "'{}'::text[]" },
	title: { label: 'Title', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
	updated_at: { label: 'Updated at', type: 'datetime', required: false, selectable: true, editable: true, insertable: true, updatable: true, hidden: true, nullable: false, hasDefault: true, databaseType: "timestamp with time zone", defaultExpression: "now()" },
} as const satisfies Partial<Record<keyof PlaylistsRow, EntityField>>

export const PlaylistsRelations: EntityRelation[] = [
  {
    "alias": "tracks",
    "kind": "hasMany",
    "direction": "inverse",
    "nullable": false,
    "referencedTable": "tracks",
    "embedResource": "tracks",
    "localColumns": [
      "id"
    ],
    "referencedColumns": [
      "playlist_id"
    ],
    "foreignKeyName": "tracks_playlist_id_fkey",
    "composite": false
  }
]
