// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type PostsRow = Tables<'posts'>

/** ----- Schema (entities) for posts ----- */
export const PostsSchema = {
	author_id: { label: 'Author id', type: 'relation', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "uuid", defaultExpression: null, relation: { alias: 'author', kind: 'belongsTo', direction: 'forward', referencedTable: 'authors', embedResource: 'authors', localColumns: ['author_id'], referencedColumns: ['id'], foreignKeyName: 'posts_author_id_fkey', nullable: false, composite: false } },
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	title: { label: 'Title', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
} as const satisfies Partial<Record<keyof PostsRow, EntityField>>

export const PostsRelations: EntityRelation[] = [
  {
    "alias": "author",
    "kind": "belongsTo",
    "direction": "forward",
    "nullable": false,
    "referencedTable": "authors",
    "embedResource": "authors",
    "localColumns": [
      "author_id"
    ],
    "referencedColumns": [
      "id"
    ],
    "foreignKeyName": "posts_author_id_fkey",
    "composite": false
  }
]
