// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type ProfilesRow = Tables<'profiles'>

/** ----- Schema (entities) for profiles ----- */
export const ProfilesSchema = {
	created_at: { label: 'Created at', type: 'datetime', required: false, selectable: true, editable: true, insertable: true, updatable: true, hidden: true, nullable: false, hasDefault: true, databaseType: "timestamp with time zone", defaultExpression: "now()" },
	display_name: { label: 'Display name', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
} as const satisfies Partial<Record<keyof ProfilesRow, EntityField>>

export const ProfilesRelations: EntityRelation[] = []
