// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type TagsRow = Tables<'tags'>

/** ----- Schema (entities) for tags ----- */
export const TagsSchema = {
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	name: { label: 'Name', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
} as const satisfies Partial<Record<keyof TagsRow, EntityField>>

export const TagsRelations: EntityRelation[] = []
