// @generated by @lucashw68/nsdb - DO NOT EDIT.
import type { Tables } from '~~/types/database.types'
import type { EntityField, EntityRelation } from '@lucashw68/nsdb/types/entities'
import * as Enums from '~~/nsdb/enums'

// Convenience row type for this table (optional)
export type TracksRow = Tables<'tracks'>

/** ----- Schema (entities) for tracks ----- */
export const TracksSchema = {
	created_at: { label: 'Created at', type: 'datetime', required: false, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: true, databaseType: "timestamp with time zone", defaultExpression: "now()" },
	id: { label: 'Id', type: 'text', required: false, selectable: true, editable: true, insertable: true, updatable: false, primaryKey: true, nullable: false, hasDefault: true, databaseType: "uuid", defaultExpression: "gen_random_uuid()" },
	playlist_id: { label: 'Playlist id', type: 'relation', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "uuid", defaultExpression: null, relation: { alias: 'playlist', kind: 'belongsTo', direction: 'forward', referencedTable: 'playlists', embedResource: 'playlists', localColumns: ['playlist_id'], referencedColumns: ['id'], foreignKeyName: 'tracks_playlist_id_fkey', nullable: false, composite: false } },
	position: { label: 'Position', type: 'number', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "integer", defaultExpression: null },
	title: { label: 'Title', type: 'text', required: true, selectable: true, editable: true, insertable: true, updatable: true, nullable: false, hasDefault: false, databaseType: "text", defaultExpression: null },
} as const satisfies Partial<Record<keyof TracksRow, EntityField>>

export const TracksRelations: EntityRelation[] = [
  {
    "alias": "playlist",
    "kind": "belongsTo",
    "direction": "forward",
    "nullable": false,
    "referencedTable": "playlists",
    "embedResource": "playlists",
    "localColumns": [
      "playlist_id"
    ],
    "referencedColumns": [
      "id"
    ],
    "foreignKeyName": "tracks_playlist_id_fkey",
    "composite": false
  }
]
