import fs from 'node:fs'
import path from 'node:path'

export const GENERATED_FILE_MARKER = '// @generated by @lucashw68/nsdb - DO NOT EDIT.'

export function markGenerated(content) {
	const normalizedContent = String(content).replace(/^\uFEFF/, '')
	if (normalizedContent.startsWith(GENERATED_FILE_MARKER)) return normalizedContent
	return `${GENERATED_FILE_MARKER}\n${normalizedContent}`
}

export function isNsdbGeneratedFile(filePath) {
	if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) return false
	const descriptor = fs.openSync(filePath, 'r')
	try {
		const buffer = Buffer.alloc(256)
		const bytesRead = fs.readSync(descriptor, buffer, 0, buffer.length, 0)
		return buffer.subarray(0, bytesRead).toString('utf8').includes(GENERATED_FILE_MARKER)
	} finally {
		fs.closeSync(descriptor)
	}
}

export function listGeneratedFiles(directoryPath) {
	if (!fs.existsSync(directoryPath) || !fs.statSync(directoryPath).isDirectory()) return []

	return fs.readdirSync(directoryPath, { withFileTypes: true }).flatMap((entry) => {
		const entryPath = path.join(directoryPath, entry.name)
		if (entry.isDirectory()) return listGeneratedFiles(entryPath)
		return entry.isFile() && isNsdbGeneratedFile(entryPath) ? [entryPath] : []
	})
}

export function removeGeneratedFile(filePath, { dryRun = false, verbose = false } = {}) {
	if (!isNsdbGeneratedFile(filePath)) return false
	if (!dryRun) fs.unlinkSync(filePath)
	if (verbose || dryRun) {
		console.log(`${dryRun ? 'Would remove' : 'Removed'} generated file: ${path.relative(process.cwd(), filePath)}`)
	}
	return true
}

export function removeStaleGeneratedFiles(directoryPath, retainedFileNames) {
	const retained = new Set(retainedFileNames)
	for (const filePath of listGeneratedFiles(directoryPath)) {
		if (!retained.has(path.basename(filePath))) fs.unlinkSync(filePath)
	}
}
