<template>
	<div>
		<h1>
			💾 Example NSDB
		</h1>

		<ul>
			<li>
				<NuxtLink to="/api" class="hover:cursor:pointer hover:text-purple-500">🎯 CRUD Direct API</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					Use of the <code class="font-mono text-[0.9em] bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">useSupabaseApi</code> composable to perform direct API calls to Supabase.
				</p>
			</li>

			<li>
				<NuxtLink to="/crud" class="hover:cursor:pointer hover:text-purple-500">📦 CRUD With Models</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					Use of the <code class="font-mono text-[0.9em] bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">useSupabaseModel</code> composable abstraction to enhance even more the simplicity of CRUD operations.
				</p>
			</li>

			<li>
				<NuxtLink to="/store" class="hover:cursor:pointer hover:text-purple-500">🗄️ Store</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					Use of the Pinia stores generated by NSDB for entity management.
				</p>
			</li>

			<li>
				<NuxtLink to="/components" class="hover:cursor:pointer hover:text-purple-500">👁️ Components</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					Use of the NSDB ready-to-use Vue components for listing and editing entities
				</p>
			</li>

			<li>
				<NuxtLink to="/storage" class="hover:cursor:pointer hover:text-purple-500">Storage API</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					Use of the <code class="font-mono text-[0.9em] bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded">useSupabaseApiStorage</code> composable to interact with Supabase Storage.
				</p>
			</li>

			<li>
				<NuxtLink to="/ownership" class="hover:cursor:pointer hover:text-purple-500">Profiles, RLS and ownership</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					Recommended Supabase-first pattern for user-owned data with NSDB.
				</p>
			</li>

		</ul>

		<h1 class="mt-12">
			Documentation
		</h1>

		<ul>
			<li>
				<NuxtLink to="/bootstrap" class="hover:cursor:pointer hover:text-purple-500">🚀 Get started</NuxtLink>
				<p class="text-sm pl-4 text-gray-500">
					How to bootstrap NSDB in your Nuxt 3/4 project.
				</p>
			</li>
		</ul>

	</div>
</template>
