// @generated by @lucashw68/nsdb - DO NOT EDIT.
// Source: Database["public"]["Enums"]

import type { Database } from '~~/types/database.types'

// Enum: playlist_status
export type PlaylistStatus = Database['public']['Enums']['playlist_status']
export const PlaylistStatusValues = ["draft","published"] as const

export const Enums = {
	'playlist_status': PlaylistStatusValues
} as const
