// @generated by @lucashw68/nsdb - DO NOT EDIT.
// Source: Database["public"]["Enums"]

import type { Database } from '~~/types/database.types'

// Enum: PROVIDERS
export type PROVIDERS = Database['public']['Enums']['PROVIDERS']
export const PROVIDERSValues = ["mysic","youtube","soundcloud","spotify"] as const

// Enum: playlist_status
export type PlaylistStatus = Database['public']['Enums']['playlist_status']
export const PlaylistStatusValues = ["draft","published"] as const

export const Enums = {
	'PROVIDERS': PROVIDERSValues,
	'playlist_status': PlaylistStatusValues
} as const
