// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { AuthorsRelations, AuthorsSchema } from '~~/nsdb/schemas/authors'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useAuthorStore } from '~~/stores/useAuthorStore'

export type AuthorsRow = Omit<Tables<'authors'>, never>
export type AuthorsInsert = Omit<TablesInsert<'authors'>, never>
export type AuthorsUpdate = Omit<TablesUpdate<'authors'>, 'id'>
export type AuthorsRelationRows = {
	'receiver_messages': Omit<Tables<'messages'>, never>[]
	'sender_messages': Omit<Tables<'messages'>, never>[]
	'posts': Omit<Tables<'posts'>, never>[]
}

export function useAuthors(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<AuthorsRow, AuthorsInsert, AuthorsUpdate, 'id'>(
		'authors',
		{ store: !!opts.store, storeCreator: (() => useAuthorStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(AuthorsSchema, AuthorsRelations);

	const { fetch, refresh } = bindModel<AuthorsRow, AuthorsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: AuthorsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
