// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { CategoriesRelations, CategoriesSchema } from '~~/nsdb/schemas/categories'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useCategorieStore } from '~~/stores/useCategorieStore'

export type CategoriesRow = Omit<Tables<'categories'>, never>
export type CategoriesInsert = Omit<TablesInsert<'categories'>, never>
export type CategoriesUpdate = Omit<TablesUpdate<'categories'>, 'id'>
export type CategoriesRelationRows = {
	'parent': Omit<Tables<'categories'>, never> | null
	'children': Omit<Tables<'categories'>, never>[]
}

export function useCategories(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<CategoriesRow, CategoriesInsert, CategoriesUpdate, 'id'>(
		'categories',
		{ store: !!opts.store, storeCreator: (() => useCategorieStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(CategoriesSchema, CategoriesRelations);

	const { fetch, refresh } = bindModel<CategoriesRow, CategoriesRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: CategoriesSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
