// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { ComponentRecordsRelations, ComponentRecordsSchema } from '~~/nsdb/schemas/component_records'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useComponentRecordStore } from '~~/stores/useComponentRecordStore'

export type ComponentRecordsRow = Omit<Tables<'component_records'>, 'user_id'>
export type ComponentRecordsInsert = Omit<TablesInsert<'component_records'>, 'user_id'>
export type ComponentRecordsUpdate = Omit<TablesUpdate<'component_records'>, 'id' | 'user_id'>
export type ComponentRecordsRelationRows = {}

export function useComponentRecords(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<ComponentRecordsRow, ComponentRecordsInsert, ComponentRecordsUpdate, 'id'>(
		'component_records',
		{ store: !!opts.store, storeCreator: (() => useComponentRecordStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(ComponentRecordsSchema, ComponentRecordsRelations);

	const { fetch, refresh } = bindModel<ComponentRecordsRow, ComponentRecordsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: ComponentRecordsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
