// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { GearsRelations, GearsSchema } from '~~/nsdb/schemas/gears'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useGearStore } from '~~/stores/useGearStore'

export type GearsRow = Omit<Tables<'gears'>, never>
export type GearsInsert = Omit<TablesInsert<'gears'>, 'created_at' | 'id' | 'updated_at'>
export type GearsUpdate = Omit<TablesUpdate<'gears'>, 'created_at' | 'id' | 'updated_at'>
export type GearsRelationRows = {}

export function useGears(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<GearsRow, GearsInsert, GearsUpdate>(
		'gears',
		{ store: !!opts.store, storeCreator: (() => useGearStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(GearsSchema, GearsRelations);

	const { fetch, refresh } = bindModel<GearsRow, GearsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: GearsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
