// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { MessagesRelations, MessagesSchema } from '~~/nsdb/schemas/messages'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useMessageStore } from '~~/stores/useMessageStore'

export type MessagesRow = Omit<Tables<'messages'>, never>
export type MessagesInsert = Omit<TablesInsert<'messages'>, never>
export type MessagesUpdate = Omit<TablesUpdate<'messages'>, 'id'>
export type MessagesRelationRows = {
	'receiver': Omit<Tables<'authors'>, never>
	'sender': Omit<Tables<'authors'>, never>
}

export function useMessages(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<MessagesRow, MessagesInsert, MessagesUpdate, 'id'>(
		'messages',
		{ store: !!opts.store, storeCreator: (() => useMessageStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(MessagesSchema, MessagesRelations);

	const { fetch, refresh } = bindModel<MessagesRow, MessagesRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: MessagesSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
