// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { PlaylistsRelations, PlaylistsSchema } from '~~/nsdb/schemas/playlists'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { usePlaylistStore } from '~~/stores/usePlaylistStore'

export type PlaylistsRow = Omit<Tables<'playlists'>, 'user_id'>
export type PlaylistsInsert = Omit<TablesInsert<'playlists'>, 'user_id'>
export type PlaylistsUpdate = Omit<TablesUpdate<'playlists'>, 'id' | 'user_id'>
export type PlaylistsRelationRows = {
	'tracks': Omit<Tables<'tracks'>, never>[]
}

export function usePlaylists(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<PlaylistsRow, PlaylistsInsert, PlaylistsUpdate, 'id'>(
		'playlists',
		{ store: !!opts.store, storeCreator: (() => usePlaylistStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(PlaylistsSchema, PlaylistsRelations);

	const { fetch, refresh } = bindModel<PlaylistsRow, PlaylistsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: PlaylistsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
