// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { PostsRelations, PostsSchema } from '~~/nsdb/schemas/posts'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { usePostStore } from '~~/stores/usePostStore'

export type PostsRow = Omit<Tables<'posts'>, never>
export type PostsInsert = Omit<TablesInsert<'posts'>, never>
export type PostsUpdate = Omit<TablesUpdate<'posts'>, 'id'>
export type PostsRelationRows = {
	'author': Omit<Tables<'authors'>, never>
}

export function usePosts(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<PostsRow, PostsInsert, PostsUpdate, 'id'>(
		'posts',
		{ store: !!opts.store, storeCreator: (() => usePostStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(PostsSchema, PostsRelations);

	const { fetch, refresh } = bindModel<PostsRow, PostsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: PostsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
