// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { ProfilesRelations, ProfilesSchema } from '~~/nsdb/schemas/profiles'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useProfileStore } from '~~/stores/useProfileStore'

export type ProfilesRow = Omit<Tables<'profiles'>, 'user_id'>
export type ProfilesInsert = Omit<TablesInsert<'profiles'>, 'user_id'>
export type ProfilesUpdate = Omit<TablesUpdate<'profiles'>, 'id' | 'user_id'>
export type ProfilesRelationRows = {}

export function useProfiles(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<ProfilesRow, ProfilesInsert, ProfilesUpdate, 'id'>(
		'profiles',
		{ store: !!opts.store, storeCreator: (() => useProfileStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(ProfilesSchema, ProfilesRelations);

	const { fetch, refresh } = bindModel<ProfilesRow, ProfilesRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: ProfilesSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
