// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { SamplesRelations, SamplesSchema } from '~~/nsdb/schemas/samples'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useSampleStore } from '~~/stores/useSampleStore'

export type SamplesRow = Omit<Tables<'samples'>, never>
export type SamplesInsert = Omit<TablesInsert<'samples'>, 'created_at' | 'id'>
export type SamplesUpdate = Omit<TablesUpdate<'samples'>, 'created_at' | 'id'>
export type SamplesRelationRows = {}

export function useSamples(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<SamplesRow, SamplesInsert, SamplesUpdate, 'id'>(
		'samples',
		{ store: !!opts.store, storeCreator: (() => useSampleStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(SamplesSchema, SamplesRelations);

	const { fetch, refresh } = bindModel<SamplesRow, SamplesRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: SamplesSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
