// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { SongsRelations, SongsSchema } from '~~/nsdb/schemas/songs'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useSongStore } from '~~/stores/useSongStore'

export type SongsRow = Omit<Tables<'songs'>, never>
export type SongsInsert = Omit<TablesInsert<'songs'>, 'created_at' | 'id'>
export type SongsUpdate = Omit<TablesUpdate<'songs'>, 'created_at' | 'id'>
export type SongsRelationRows = {}

export function useSongs(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<SongsRow, SongsInsert, SongsUpdate, 'id'>(
		'songs',
		{ store: !!opts.store, storeCreator: (() => useSongStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(SongsSchema, SongsRelations);

	const { fetch, refresh } = bindModel<SongsRow, SongsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: SongsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
