// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { TagsRelations, TagsSchema } from '~~/nsdb/schemas/tags'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useTagStore } from '~~/stores/useTagStore'

export type TagsRow = Omit<Tables<'tags'>, never>
export type TagsInsert = Omit<TablesInsert<'tags'>, never>
export type TagsUpdate = Omit<TablesUpdate<'tags'>, 'id'>
export type TagsRelationRows = {}

export function useTags(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<TagsRow, TagsInsert, TagsUpdate, 'id'>(
		'tags',
		{ store: !!opts.store, storeCreator: (() => useTagStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(TagsSchema, TagsRelations);

	const { fetch, refresh } = bindModel<TagsRow, TagsRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: TagsSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
