// @generated by @lucashw68/nsdb - DO NOT EDIT.
// __IMPORTS__
import type { Tables, TablesInsert, TablesUpdate } from '~~/types/database.types'
import { TracksRelations, TracksSchema } from '~~/nsdb/schemas/tracks'
import { useNsdbSchema } from '@lucashw68/nsdb/useNsdbSchema'
import { useTrackStore } from '~~/stores/useTrackStore'

export type TracksRow = Omit<Tables<'tracks'>, never>
export type TracksInsert = Omit<TablesInsert<'tracks'>, never>
export type TracksUpdate = Omit<TablesUpdate<'tracks'>, 'id'>
export type TracksRelationRows = {
	'playlist': Omit<Tables<'playlists'>, 'user_id'>
}

export function useTracks(opts: { store?: boolean } = {}) {
	const model = useSupabaseModel<TracksRow, TracksInsert, TracksUpdate, 'id'>(
		'tracks',
		{ store: !!opts.store, storeCreator: (() => useTrackStore() as any), primaryKey: 'id' }
	)

	const {
		fields,
		editableKeys,
		createDraftFromSchema,
		bindModel,
	} = useNsdbSchema(TracksSchema, TracksRelations);

	const { fetch, refresh } = bindModel<TracksRow, TracksRelationRows>(model)

	return {
		primaryKey: 'id' as const,
		items: model.items,
		totalCount: model.totalCount,
		loading: model.loading,
		error: model.error,
		stale: model.stale,
		schema: TracksSchema,
		fields,
		editableKeys,
		createDraft: () => createDraftFromSchema(),
		fetch,
		refresh,
		invalidate: model.invalidate,
		getById: model.getById,
		create: model.create,
		update: model.update,
		remove: model.remove,
		subscribe: model.subscribe,
		unsubscribe: model.unsubscribe,
	}
}
