#!/usr/bin/env node
/**
 * generate-tables.js
 * 
 * Goal: For each Supabase table, generate a "table module" that combines:
 *  - The Entity schema (metadata)
 *  - A typed repo/handle wrapping your existing useSupabaseModel composable
 * 
 * Output:
 *  - nsdb/tables/<table>.ts   (one per table)
 *  - nsdb/tables.ts           (barrel exporting everything)
 * 
 * How it finds tables:
 *  - It reads keys from `types/models.ts` (generated by your pipeline),
 *    falling back to `nsdb/models.ts` if not found.
 */

const fs = require('fs')
const path = require('path')

const cwd = process.cwd()

function panic(msg) {
  console.error('❌ ' + msg)
  process.exit(1)
}

function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true })
}

function pascalCase(name) {
  return name
    .replace(/[-_./]+/g, ' ')
    .replace(/\s+(\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, c => c.toUpperCase())
    .replace(/\s+/g, '')
}

function findModelsFile() {
  const candidates = [
    path.resolve(cwd, 'types/models.ts'),
    path.resolve(cwd, 'nsdb/models.ts'),
  ]
  for (const p of candidates) {
    if (fs.existsSync(p)) return p
  }
  return null
}

function parseTableNames(modelsTs) {
  const src = fs.readFileSync(modelsTs, 'utf8')

  // Look for: export const modelMap = { 'table': ..., "table2": ... }
  const mapStart = src.indexOf('modelMap')
  if (mapStart === -1) {
    console.warn('⚠️  Could not find "modelMap" in ' + modelsTs + ' — falling back to ModelTypes keys heuristic.')
  }

  // Try to match object literal keys after "modelMap"
  const mapMatch = src.match(/modelMap\s*=\s*\{([\s\S]*?)\}\s*;/)
  let keys = []
  if (mapMatch) {
    const body = mapMatch[1]
    // Matches quoted keys: 'foo': or "foo":
    const re = /['"]([\w-]+)['"]\s*:/g
    let m
    while ((m = re.exec(body))) keys.push(m[1])
  }

  // Fallback: try to read union from ModelTypes or similar
  if (keys.length === 0) {
    // naive fallback: scan for use of Tables<'X'> to infer table names
    const reT = /Tables<\s*'([\w-]+)'\s*>/g
    let m
    while ((m = reT.exec(src))) {
      if (!keys.includes(m[1])) keys.push(m[1])
    }
  }

  // Final check
  keys = Array.from(new Set(keys))
  if (keys.length === 0) {
    panic('No table names found. Make sure types/models.ts (or nsdb/models.ts) exports modelMap.')
  }

  return keys
}

function tableModuleSource(table) {
  const P = pascalCase(table)
  const Row = `${P}Row`
  const Schema = `${P}Schema`
  const useHook = `use${P}`

  return `import type { Tables } from '~/types/database.types'
import type { EntityField } from '@lucashw68/nsdb/types/entities'
import { computed } from 'vue'
import { useSupabaseModel } from '#imports'

export type ${Row} = Tables<'${table}'>

/** ----- Entities (schema) ----- */
export const ${Schema}: Record<keyof ${Row}, EntityField> = {
  // id: { type: 'uuid', pk: true, readonly: true },
  // name: { type: 'string', required: true },
} as const

function __emptyFromSchema(): Partial<${Row}> {
  const out: Record<string, any> = {}
  for (const [k, def] of Object.entries(${Schema} as Record<string, any>)) {
    out[k] = 'default' in def ? def.default : (def.type === 'boolean' ? false : null)
  }
  return out as Partial<${Row}>
}

/** ----- Repo CRUD + schema (DX handle) ----- */
export function ${useHook}(opts: { store?: boolean } = {}) {
  const model = useSupabaseModel('${table}', !!opts.store)

  const list  = model.items
  const all   = async () => {
    const rows = await model.fetch()
    list.value = Array.isArray(rows) ? rows : []
    return list.value as ${Row}[]
  }
  const find  = (id: string) => model.getById(id) as Promise<${Row} | null>
  const add   = (payload: Partial<${Row}>) => model.create(payload) as Promise<${Row} | null>
  const patch = (id: string, payload: Partial<${Row}>) => model.update(id, payload) as Promise<${Row} | null>
  const del   = (id: string) => model.remove(id)

  const fields = Object.keys(${Schema})
  const editableKeys = computed(() => Object.entries(${Schema} as Record<string, any>)
    .filter(([, d]) => !d.readonly)
    .map(([k]) => k)
  )

  return {
    // state
    list,
    // schema + helpers
    schema: ${Schema},
    fields,
    editableKeys,
    new: () => __emptyFromSchema(),
    // crud
    all, find, add, patch, remove: del,
  }
}
`
}

function main() {
  const modelsFile = findModelsFile()
  if (!modelsFile) {
    panic('Cannot find types/models.ts or nsdb/models.ts. Run your nsdb:models generator first.')
  }
  const tables = parseTableNames(modelsFile)

  const outDir = path.resolve(cwd, 'nsdb/tables')
  ensureDir(outDir)

  // Generate per-table module
  for (const t of tables) {
    const file = path.join(outDir, `${t}.ts`)
    const src = tableModuleSource(t)
    fs.writeFileSync(file, src, 'utf8')
    console.log('✅ wrote', path.relative(cwd, file))
  }

  // Barrel
  const barrel = path.resolve(cwd, 'nsdb/tables.ts')
  const lines = tables.map(t => {
    const P = pascalCase(t)
    return `export * from './tables/${t}' // use${P}, ${P}Schema`
  })
  fs.writeFileSync(barrel, lines.join('\n') + '\n', 'utf8')
  console.log('✅ wrote', path.relative(cwd, barrel))

  console.log('🎉 Done. Import with:  import { usePlaylists, PlaylistsSchema } from "#nsdb/tables"')
}

if (require.main === module) {
  main()
}
