// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type AuthorsRow = Tables<'authors'>

export const useAuthorStore = createDbStore<AuthorsRow>('authors', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
