// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type ComponentRecordsRow = Tables<'component_records'>

export const useComponentRecordStore = createDbStore<ComponentRecordsRow>('component_records', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
