// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type CategoriesRow = Tables<'categories'>

export const useCategorieStore = createDbStore<CategoriesRow>('categories', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
