// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type MessagesRow = Tables<'messages'>

export const useMessageStore = createDbStore<MessagesRow>('messages', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
