// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type PostsRow = Tables<'posts'>

export const usePostStore = createDbStore<PostsRow>('posts', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
