// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type TagsRow = Tables<'tags'>

export const useTagStore = createDbStore<TagsRow>('tags', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
