// @generated by @lucashw68/nsdb - DO NOT EDIT.
import { createDbStore } from '@lucashw68/nsdb/createDbStore'
import type { Tables } from '~~/types/database.types'

type TracksRow = Tables<'tracks'>

export const useTrackStore = createDbStore<TracksRow>('tracks', {
	key: 'id',
	orderBy: 'id',
	defaultSort: 'desc',
})
