create table public.schema_features (
  slug text primary key,
  sequence_id bigint generated always as identity unique,
  sequence_by_default bigint generated by default as identity unique,
  uuid_default uuid not null default gen_random_uuid(),
  required_field text not null,
  nullable_field text,
  custom_default text not null default 'hello',
  state public.playlist_status not null default 'draft',
  payload jsonb not null default '{}'::jsonb,
  labels text[] not null default '{}',
  created_on timestamptz not null default now(),
  computed_label text generated always as (slug || ':' || required_field) stored
);

create table public.authors (
  id uuid primary key default gen_random_uuid(),
  name text not null unique
);

create table public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.authors(id),
  title text not null
);

create table public.tags (
  id uuid primary key default gen_random_uuid(),
  name text not null unique
);

create table public.post_tags (
  post_id uuid not null references public.posts(id) on delete cascade,
  tag_id uuid not null references public.tags(id) on delete cascade,
  primary key (post_id, tag_id)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.authors(id),
  receiver_id uuid not null references public.authors(id),
  body text not null
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.categories(id),
  name text not null
);

create table public.composite_parents (
  tenant_id uuid not null,
  code text not null,
  label text not null,
  primary key (tenant_id, code)
);

create table public.composite_children (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null,
  parent_code text not null,
  foreign key (tenant_id, parent_code)
    references public.composite_parents (tenant_id, code)
);

insert into public.authors (id, name)
values
  ('10000000-0000-0000-0000-000000000001', 'Ada'),
  ('10000000-0000-0000-0000-000000000002', 'Grace');

insert into public.posts (id, author_id, title)
values ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', 'Typed bridges');

insert into public.tags (id, name)
values
  ('30000000-0000-0000-0000-000000000001', 'nuxt'),
  ('30000000-0000-0000-0000-000000000002', 'supabase');

insert into public.post_tags (post_id, tag_id)
values
  ('20000000-0000-0000-0000-000000000001', '30000000-0000-0000-0000-000000000001'),
  ('20000000-0000-0000-0000-000000000001', '30000000-0000-0000-0000-000000000002');

insert into public.messages (sender_id, receiver_id, body)
values ('10000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000002', 'Hello');

insert into public.categories (id, parent_id, name)
values
  ('40000000-0000-0000-0000-000000000001', null, 'Root'),
  ('40000000-0000-0000-0000-000000000002', '40000000-0000-0000-0000-000000000001', 'Child');

insert into public.composite_parents (tenant_id, code, label)
values ('50000000-0000-0000-0000-000000000001', 'parent', 'Composite parent');

insert into public.composite_children (tenant_id, parent_code)
values ('50000000-0000-0000-0000-000000000001', 'parent');
